name: CI Pipeline
 
on:
  push:
    branches:
      - main  # Ou a branch principal do seu projeto
  pull_request:
    branches:
      - main  # Para rodar o pipeline quando um PR for aberto
 
jobs:
  test:
    runs-on: ubuntu-latest  # Usando uma máquina virtual Ubuntu para rodar os testes
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Faz o checkout do código do repositório
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Defina a versão do Python que você está utilizando
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala todas as dependências do projeto
    
    - name: Run unit tests (test_escolha.py)
      run: |
        pytest tests/test_escolha.py --maxfail=1 --disable-warnings -q  # Executa os testes unitários
 
    - name: Run functional tests (test_funcional.py)
      run: |
        pytest tests/test_funcional.py --maxfail=1 --disable-warnings -q  # Executa os testes funcionais
    
    - name: Run integration tests (test_integracao.py)
      run: |
        pytest tests/test_integracao.py --maxfail=1 --disable-warnings -q  # Executa os testes de integração
 
    - name: Run performance tests (test_desempenho.py)
      run: |
        pytest tests/test_desempenho.py --maxfail=1 --disable-warnings -q  # Executa os testes de desempenho
